version: '3.8'

services:
  # Metabase for visualization with DuckDB support
  metabase:
    build: ./docker/metabase
    container_name: metabase
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres
      # Add Java options for better DuckDB performance
      JAVA_OPTS: "-Xmx4g -Xms1g"
    depends_on:
      - postgres
    volumes:
      - metabase-data:/metabase-data
      - ./data:/data:ro  # Mount our data directory for DuckDB access

  # Postgres for Metabase metadata
  postgres:
    image: postgres:15-alpine
    container_name: metabase_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # DuckDB (for development - will be added when we build the API)
  # duckdb:
  #   build: ./src/api
  #   container_name: duckdb_api
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./data:/data

volumes:
  metabase-data:
  postgres-data: