name: dataeng

type: python:3.11

size: M

relationships:
  clickhouse_db: "clickhouse:main_endpoint"

hooks:
  build: |
    pip install -r requirements.txt

disk: 5120

mounts:
  "/storage":
    source: local
    source_path: "storage"