clickhouse:
  type: clickhouse:23
  disk: 5120
  configuration:
    databases:
      - default
    endpoints:
      main_endpoint:
        default_database: default
        port: 8123
        privileges:
          default: admin
      ro:
        default_database: default
        port: 8123
        privileges:
          default: ro