# Site settings
title: "Open FinOps Stack"
description: "Open source FinOps platform with FOCUS-first architecture"
baseurl: "/open-finops-stack"
url: "https://jgrubb.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Navigation
header_pages:
  - getting-started/index.md
  - user-guide/index.md
  - deployment/index.md
  - development/index.md
  - reference/index.md

# Collections
collections:
  getting_started:
    output: true
    permalink: /:collection/:name/
  user_guide:
    output: true
    permalink: /:collection/:name/
  deployment:
    output: true
    permalink: /:collection/:name/
  development:
    output: true
    permalink: /:collection/:name/
  reference:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/